### ISSUE TITLE
Text file not uploading

### ISSUE THREAD

**Issue by ravindrasail** [ajeetAk47/DigiBoard#1]
This very nice and creative app bro.  I tried to upload .Text file but it's not uploading. Please fix it. Happy coding

**Comment by imajeetyadav** [comment]
Ok i will check

**Comment by imajeetyadav** [comment]
I checked text file uploading feature but i am not any issue.You are facing  this  issue may be the  reason behind is that your file content is not in the predefined format specified there. Please check the predefined format.
We are looking for better solution for this.

**Comment by ravindrasail** [comment]
Please share .txt file with me
